import React, { useEffect, useRef, useState } from 'react';
import Head from "next/head";
import styled, { css } from 'styled-components';

import { sizes } from '../constants/sizes';

const metadata = require('../public/fonts/bravura/bravura_metadata.json');

const Wrapper = styled.main`
  display: grid;
  width: 100%;
  height: 100%;
  min-height: 100vh;
  padding: 20mm;
  place-items: start start;
`;

const Score = styled.article`
  display: grid;
  grid-auto-flow: row;
  row-gap: ${sizes.FONT * 3}mm;
  width: 100%;
`

const System = styled.section`
  position: relative;
  display: grid;
  place-items: start start;
  // column name: cumulative duration (timestamp)
  // event-{timestamp}-cle: clef
  // event-{timestamp}-tim: time signature
  // event-{timestamp}-key: key signature
  // event-{timestamp}-art={art index}: left-hand articulation(s) (e.g. arpeggio)
  // event-{timestamp}-acc-{acc index}: accidental(s)
  // column width: event duration @ timestamp
  grid-template-columns: [system-start staff-0-start staff-1-start staff-2-start staff-3-start event-label-start] auto [event-label-end event-0-cle-start] auto [event-0-cle-end event-0-tim-start] auto [event-0-tim-end event-0-start] 1024fr [event-0-end event-1024-cle-start] auto [event-1024-cle-end event-1024-tim-start] auto [event-1024-tim-end event-1024-start] 512fr [event-1024-end event-2048-cle-start] auto [event-2048-cle-end event-2048-tim-start] auto [event-2048-tim-end event-2048-start] 1024fr [event-2048-end staff-3-end staff-2-end staff-1-end staff-0-end system-end];
  // rows: one row per staff
  grid-template-rows: [system-start staff-0-start] auto [staff-0-end staff-1-start] auto [staff-1-end system-end];
  // additional staff gap can be applied via padding/margin
  row-gap: ${sizes.FONT * 1.5}mm;
`

const Staff = styled.div`
  ${({ $gridArea, $spaces = 4, }) => css`
    grid-area: ${$gridArea};
    width: 100%;
    height: ${sizes.FONT}mm;
    /* background: yellow; */
    display: grid;
    place-items: center start;
    grid-template-columns: subgrid;
    // TODO: rows here should be generated by way of intersection of clef and octave displacement
    grid-template-rows: [d6-start] 0 [d6-end c6-start] 0 [c6-end b5-start] 0 [b5-end a5-start] 0 [a5-end g5-start] 0 [g5-end f5-start] 0 [f5-end e5-start] 0 [e5-end d5-start] 0 [d5-end c5-start] 0 [c5-end b4-start center-start] 0 [center-end b4-end a4-start] 0 [a4-end g4-start] 0 [g4-end f4-start] 0 [f4-end e4-start] 0 [e4-end d4-start] 0 [d4-end c4-start] 0 [c4-end b3-start] 0 [b3-end a3-start] 0 [a3-end g3-start] 0 [g3-end];
    row-gap: ${sizes.FONT / ($spaces * 2)}mm;
    align-content: center;
    & > ${Item} {
      padding-left: 1mm;
    }
  `}
`

const StaffLine = styled.hr`
  align-self: start;
  width: 100%;
  height: 0;
  border-width: ${metadata.engravingDefaults.staffLineThickness * (sizes.FONT / 4)}mm;
  border-style: solid;
  border-bottom: none;
  margin: 0;
  ${({ $pitch, $start, $end }) => css`
    grid-row: ${$pitch} / ${$pitch};
    grid-column-start: event-${$start};
    grid-column-end: event-${$end};
  `}
`

const Label = styled.span`
  grid-row: center;
  font-family: Inter, sans-serif;
  font-size: ${sizes.FONT / 2}mm;
  padding-right: ${sizes.FONT / 2}mm;
  height: 0;
  display: flex;
  align-items: center;
  justify-self: flex-end;
`

const Item = styled.span`
  ${({ $pitch, $start, $padEnd }) => css`
    grid-row: ${$pitch};
    grid-column: event-${$start};
    align-self: center;
    height: 0;
    display: flex;
    align-items: center;
    font-family: Bravura, sans-serif;
    padding-right: ${$padEnd}mm;
  `}
`

const Barline = styled.svg.attrs(() => ({
  viewBox: `0 0 1 1`,
  preserveAspectRatio: 'none',
  width: `${metadata.engravingDefaults.staffLineThickness * (sizes.FONT / 4)}mm`,
  height: '100%',
  overflow: 'visible',
}))`
  ${({ $column }) => css`
    grid-row: system;
    grid-column: event-${$column};
    justify-self: end;
    height: 100%;
  `}
`

export default function EditorPage() {
  return (
    <Wrapper>
      <Head />
      <p>This is a test page.</p>
      <Score>
        <System>
          <Barline $row="system" $column="label">
            <rect width={`${metadata.engravingDefaults.staffLineThickness * (sizes.FONT / 4)}mm`} height="100%" fill="black" />
          </Barline>
          <Staff $gridArea={'staff-0'}>
            <Label $pitch="center" $start={'label'}>Violin I</Label>
            <StaffLine $pitch="f5" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="d5" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="b4" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="g4" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="e4" $start={'0-cle'} $end={2048} />
            <Item $pitch="g4" $start={'0-cle'} $padEnd={1}></Item>
            <Item $pitch="center" $start={'0-tim'} $padEnd={1}></Item>
            <Item $pitch="c6" $start={0}></Item>
            <Item $pitch="g3" $start={1024}></Item>
            <Item $pitch="a4" $start={2048}></Item>
          </Staff>
          <Staff $gridArea={'staff-1'}>
            <Label $pitch="center" $start={'label'}>Violin II</Label>
            <StaffLine $pitch="f5" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="d5" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="b4" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="g4" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="e4" $start={'0-cle'} $end={2048} />
            <Item $pitch="g4" $start={'0-cle'} $padEnd={1}></Item>
            <Item $pitch="e5" $start={1024}></Item>
            <Item $pitch="f4" $start={2048}></Item>
          </Staff>
        </System>
        <System>
          <Barline $row="system" $column="label">
            <rect width={`${metadata.engravingDefaults.staffLineThickness * (sizes.FONT / 4)}mm`} height="100%" fill="black" />
          </Barline>
          <Staff $gridArea={'staff-0'}>
            <StaffLine $pitch="f5" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="d5" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="b4" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="g4" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="e4" $start={'0-cle'} $end={2048} />
            <Label $pitch="center" $start={'label'}>Vln.I</Label>
            <Item $pitch="g4" $start={'0-cle'} $padEnd={1}></Item>
            <Item $pitch="c6" $start={0}></Item>
            <Item $pitch="g3" $start={1024}></Item>
            <Item $pitch="a4" $start={2048}></Item>
          </Staff>
          <Staff $gridArea={'staff-1'}>
            <StaffLine $pitch="f5" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="d5" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="b4" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="g4" $start={'0-cle'} $end={2048} />
            <StaffLine $pitch="e4" $start={'0-cle'} $end={2048} />
            <Label $pitch="center" $start={'label'}>Vln.II</Label>
            <Item $pitch="g4" $start={'0-cle'} $padEnd={1}></Item>
            <Item $pitch="e5" $start={1024}></Item>
            <Item $pitch="f4" $start={2048}></Item>
          </Staff>
        </System>
      </Score>
    </Wrapper>
  )
}